config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :inquiry, only: %i[new create]
  resources :daily_workouts, only: %i[new create], path: '/daily_workouts'
  resources :monthly_workouts, only: %i[new create], path: '/monthly_workouts'
  root 'home#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_workout.rb
# == Schema Information
#
# Table name: daily_workouts
#
#  id         :integer          not null, primary key
#  focus      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class DailyWorkout < ApplicationRecord
  has_many :workouts
  accepts_nested_attributes_for :workouts
end

app/models/inquiry.rb
# == Schema Information
#
# Table name: inquiries
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  goals      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :goals, presence: true

  def send_mail
    InquiryMailer.with(inquiry: self).inquiry_mail.deliver_now
  end



end

app/models/monthly_workout.rb
class MonthlyWorkout < ApplicationRecord
  has_one_attached :monthly_plan

  # not returning the right boolean
  # upload an image of the monthly plan pdf is too much work
  def monthly_plan?
    monthly_plan.attached?
  end
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Video < ApplicationRecord
  has_one_attached :video
  validates :video, presence: true
  validates :title, presence: true
end

app/models/workout.rb
# == Schema Information
#
# Table name: workouts
#
#  id               :integer          not null, primary key
#  lift             :string
#  sets             :integer
#  reps             :integer
#  daily_workout_id :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Workout < ApplicationRecord
  belongs_to :daily_workout
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_workouts_controller.rb
class DailyWorkoutsController < ApplicationController

  def new
    @daily_workout = DailyWorkout.new
    @daily_workout.workouts.build
  end

  def create
    @daily_workout = DailyWorkout.create(daily_workout_params)
    if @daily_workout.save
      flash[:success] = "A daily Workout Was Created !"
      redirect_to root_path
    end
  end

  private
  def daily_workout_params
    params.require(:daily_workout).permit(:focus, workouts_attributes: %i[lift sets reps])
  end

end

#todo align table in center under daily Workout title, wrap focus in if statement ( in case its left out ), remove margin/padding
# under the carousel then begin file uploads

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
        @daily_workout = DailyWorkout.last if DailyWorkout.last
        @monthly_workout = MonthlyWorkout.last
  end

end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      @inquiry.send_mail
      flash[:success] = 'Thank You! We will get in touch with you shortly'
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(%i[name email goals])
  end

end

app/controllers/monthly_workouts_controller.rb
class MonthlyWorkoutsController < ApplicationController

  def new
    @monthly_workout = MonthlyWorkout.new
  end

  def create
    @monthly_workout = MonthlyWorkout.new
    if @monthly_workout.save
      flash[:success] = "Monthly Workout Uploaded"
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  # todo paginate, add sthumbnail to video => prevents video from being played in index
  # sho is aonly available to memebrs 
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video was successfully created.'
      redirect_to videos_path
    else
     render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
      if @video.update(video_params)
        flash[:success] = 'Video was succesfully updated'
        redirect_to videos_path
      else 
        render :edit, status: :unprocessable_entity 
      end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    # TODO flash confirmation
    @video.destroy
    redirect_to videos_url, notice: 'Video was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def video_params
    params.require(:video).permit(%i[title video])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_workouts_helper.rb
module DailyWorkoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/monthly_workouts_helper.rb
module MonthlyWorkoutsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/home.html.erb
<div class="relative bg-white overflow-hidden">
  <div class="max-w-7xl mx-auto">
    <div class="relative z-5 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32"><div>
    </div>
      <main class="mt-10 max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
          <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Train With</span>
            <span class="block text-blue-500 xl:inline">Jack</span>
          </h1>
          <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
            Build Your Dream Body
          </p>
          <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
              <% if @monthly_workout && @monthly_workout.monthly_plan? %>
                <button class="inline-flex items-center justify-center px-5 py-3 border
        border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  <%= link_to"Workout Plan", @monthly_workout.monthly_plan.preview %>
                </button>
              <% end %>
            <div class="mt-3 sm:mt-0 sm:ml-3">
              <%= link_to "Get Started", new_inquiry_path, class: "w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 md:py-4 md:text-lg md:px-10" %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
  <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
    <%= image_tag image_path("julioheader.jpg"), class: 'h-56 w-full object-cover sm:h-full md:h-64 lg:w-full lg:h-full' %>
  </div>
</div>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="py-12 bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center">
      <h2 class="text-base text-blue-600 font-semibold tracking-wide uppercase">Fitness</h2>
      <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
        Create a Healthy Life
      </p>
      <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">

      </p>
    </div>

    <div class="mt-10">
      <dl class="space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10">
        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/globe-alt -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Online Catalog</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">
            Get full Access to our exclusive online fitness tutorial catalog by becoming a premium member <a class="text-blue-600 font-semibold hover:text-blue-700" href="">today.</a>
          </dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/scale -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Balance Your Lifestyle</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">
           Our certified specialist can help you achieve your fitness goals and become the best version of yourself.
          </dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/lightning-bolt -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Look Great</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">
            Our custom workout plan will help you build muscle, drop fat and gain the confidence you've always wanted.
          </dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/annotation -->
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Boost Your Mood</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">
            Fitness isn't just about looks. <a class="text-blue-600 font-semibold hover:text-blue-700" href="https://www.researchgate.net/publication/232569085_The_Effects_of_Exercise_on_Mood_in_Older_Adults_A_Meta-Analytic_Review">
            Scientific research</a>
            has shown that exercise provides a plethora of benefits like anti-aging, increased cognition and positive mood!
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>

<% if @daily_workout %>
  <div class="py-12 bg-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="lg:text-center">
        <h2 class="text-base text-blue-600 font-semibold tracking-wide uppercase">Today's Workout</h2>
        <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
          <%= @daily_workout.focus %>
        </p>
        <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">

        </p>
      </div>
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Lift
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Sets
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Reps
          </th>
        </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
        <% @daily_workout.workouts.each do |workout| %>
          <tr>
            <td class="px-6 py-4 whitespace-nowrap">
              <div>
                <h2 class="text-base text-blue-600 font-medium tracking-wide">
                  <%= workout.lift %>
                </h2>
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm font-medium text-gray-900">
                <p class=" text-lg leading-6 font-medium text-gray-900"><%= workout.sets %></p>
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm font-medium text-gray-900">
                <p class="text-lg leading-6 font-medium text-gray-900"><%= workout.reps %></p>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>


<body class="bg-white font-sans leading-normal tracking-normal">
<div class="carousel relative shadow-2xl bg-white">
  <div class="carousel-inner relative overflow-hidden w-full">

    <!--Slide 1-->
    <input class="carousel-open" type="radio" id="carousel-1" name="carousel" aria-hidden="true" hidden="" checked="checked">
    <div class="carousel-item absolute opacity-0  sm:h-72 md:h-auto">
    <%= image_tag "tredmill.jpg", class: "block h-full w-full bg-blue-500 text-white text-5xl text-center" %>
    </div>
    <label for="carousel-3" class="prev control-1 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
    <label for="carousel-2" class="next control-1 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>

    <!--Slide 2-->
    <input class="carousel-open" type="radio" id="carousel-2" name="carousel" aria-hidden="true" hidden="">
    <div class="carousel-item absolute opacity-0 sm:h-72 md:h-auto">
      <%= image_tag "yokedgirl.jpg", class: "block h-full w-full bg-blue-500 text-white text-5xl text-center" %>
    </div>
    <label for="carousel-1" class="prev control-2 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
    <label for="carousel-3" class="next control-2 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>

    <!--Slide 3-->
    <input class="carousel-open" type="radio" id="carousel-3" name="carousel" aria-hidden="true" hidden="">
    <div class="carousel-item absolute opacity-0 sm:h-72 md:h-auto">
      <%= image_tag "ropes.jpg", class: "block h-full w-full bg-blue-500 text-white text-5xl text-center" %>
    </div>
    <label for="carousel-2" class="prev control-3 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
    <label for="carousel-1" class="next control-3 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>


    <!-- Add additional indicators for each slide-->
    <ol class="carousel-indicators">
      <li class="inline-block mr-3">
        <label for="carousel-1" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
      </li>
      <li class="inline-block mr-3">
        <label for="carousel-2" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
      </li>
      <li class="inline-block mr-3">
        <label for="carousel-3" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
      </li>
    </ol>

  </div>
</div>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-gray-50">
  <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
      <span class="block">Ready to achieve your goals?</span>
      <span class="block text-blue-600">Lets get fit</span>
    </h2>
    <div class="mt-8 flex lg:mt-0 lg:flex-shrink-0">
      <div class="inline-flex rounded-md shadow">
        <%= link_to "Get Started", new_inquiry_path, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700" %>
      </div>
      <% if @monthly_workout %>
        <div class="ml-3 inline-flex rounded-md shadow">
          <%= link_to "Online Catalog", root_path, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-blue-600 bg-white hover:bg-blue-50" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/inquiry/new.html.erb
<div class="h-full">
  <div class="flex mt-to justify-center self-center">
    <div class="w-full  max-w-full">
      <div class="bg-white shadow-md rounded px-8 pt-6 ">
        <h2 class="text-center mb-4 font-semibold text-lg"> Lets Get Fit</h2>
        <%= form_for @inquiry, url: inquiry_index_path do |f| %>
          <% if @inquiry.errors.any? %>
            <%= render 'layouts/shared_errors', object: @inquiry %>
            <% end %>
            <div class="mb-4">
              <%= f.label :name, class: "block text-gray-700 text-sm font-bold" %>
              <%= f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", autofocus: true, autocomplete: "name"  %>
            </div>

            <div class="mb-4">
              <%= f.label :email, class: "block text-gray-700 text-sm font-bold" %>
              <%= f.text_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", autofocus: true, autocomplete: "name"  %>
            </div>

            <div class="mb-4">
              <%= f.label "My Goals", class: "block text-gray-700 text-sm font-bold" %>
              <%= f.text_area :goals, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", autofocus: true, autocomplete: "name"  %>
            </div>

            <div class="mb-6 grid grid-cols-1 flex justify-between items-center">
              <%= f.submit "Get Started", class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700" %>
            </div>
          <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div>
  <div class="antialiased bg-gray-100 dark-mode:bg-gray-900">
    <div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
      <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
        <div class="flex flex-row items-center justify-between p-4">
          <%= link_to "Train With Jack", root_path, class: 'text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline' %>
          <button class="rounded-lg md:hidden focus:outline-none focus:shadow-outline" @click="open = !open">
            <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
              <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
              <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
          </button>
        </div>
        <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
          <%= link_to "Get Started", new_inquiry_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
          <%= link_to "Video Catalog", root_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shared_errors.html.erb
<div class="bg-red-200">
  <h2 class="p-2 font-medium">
    <%= pluralize(object.errors.count, "error") %>
    prohibited this <%= object.class %> from being saved:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="p-2 font-bold"><%= message  %></li>
      <% end %>
    </ul>
  </h2>
</div>

app/views/videos/index.html.erb
<div class="py-12 bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center">
      <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Julio's Online Workout Catalog</h2>
      <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
        The Latest Fitness Tips & Health Tricks
      </p>
      <p class="mt-4 max-w-2xl lg:mx-auto">
        <%= link_to "Add A Video", new_video_path, class: "inline-flex items-center justify-center px-5 py-3 border
         border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>
      </p>
    </div>
    <div class="mt-10 flex items-center justify-center">
      <dl class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        <% @videos.each do |video| %>
          <%= link_to video_path(video) do %>
            <div
              class="col-span-1 flex flex-col items-center
          relative bg-gray-100 py-3 px-3 rounded-3xl w-64 my-4 shadow-xl">
              <div class="rounded-lg mt-5">
                <%= video_tag url_for(video.video) %>
              </div>
              <div>
                <div class="py-5 px-5 text-center">
                  <span class="font-bold text-indigo-600 text-center text-lg"><%= video.title %></span>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </dl>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="py-12 bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center">
      <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase"><%= @video.title %></h2>
      <p class="mt-4 max-w-2xl lg:mx-auto">
      <div class="inline-flex rounded-md shadow">
        <%= link_to "Edit Video", edit_video_path(@video), class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>
      </div>
      <div class="ml-3 inline-flex rounded-md shadow">
        <%= link_to "Delete Video",root_path, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-red-600 bg-white hover:bg-red-50" %>
      </div>
      </p>
    </div>
    <div class="mt-6 px-3 py-3">
      <%= video_tag url_for(@video.video)%>
    </div>
  </div>
</div>